"""empty message

Revision ID: 4721fc8f9852
Revises: c9caa4c098ca
Create Date: 2023-12-10 17:26:30.428016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4721fc8f9852'
down_revision = 'c9caa4c098ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(length=2000), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advert', schema=None) as batch_op:
        batch_op.drop_constraint('advert_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('advert_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['create_user'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('followers_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('followers_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('post_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.drop_constraint('post_image_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('report_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('report_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['report_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['report_post_id'], ['id'])

    with op.batch_alter_table('role_permission_table', schema=None) as batch_op:
        batch_op.drop_constraint('role_permission_table_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('role_permission_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'permission', ['permission_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_constraint('work_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('work_ibfk_1', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('role_permission_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('role_permission_table_ibfk_1', 'permission', ['permission_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('role_permission_table_ibfk_2', 'role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_2', 'user', ['report_user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('report_ibfk_1', 'post', ['report_post_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_image_ibfk_1', 'post', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_2', 'board', ['board_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('post_ibfk_1', 'user', ['author_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('followers_ibfk_2', 'user', ['follower_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('followers_ibfk_1', 'user', ['followed_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_2', 'post', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('comment_ibfk_1', 'user', ['author_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('advert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('advert_ibfk_1', 'user', ['create_user'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('advert_ibfk_2', 'post', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    op.drop_table('chat')
    # ### end Alembic commands ###
