"""empty message

Revision ID: 65328f248166
Revises: 
Create Date: 2023-09-18 09:29:18.516372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65328f248166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(length=2000), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('finish', sa.Boolean(), nullable=False),
    sa.Column('timeout', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='worktypeenum'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###
