"""empty message

Revision ID: 83672dbfbc6c
Revises: 65328f248166
Create Date: 2023-09-19 19:00:42.232451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83672dbfbc6c'
down_revision = '65328f248166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
